name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'  # Specify the desired .NET version

      - name: Clean solution
        run: dotnet clean ./WebApp/WebApp/WebApplication1.sln --configuration Release

      - name: Restore packages
        run: dotnet restore ./WebApp/WebApp/WebApplication1.sln

      - name: Build application
        run: dotnet build ./WebApp/WebApp/WebApplication1.sln --configuration Release

      - name: Run tests
        run: dotnet test ./WebApp/WebApp/WebApplication1.Tests/WebApplication1.Tests.csproj --configuration Release

      - name: Deploy to staging (replace with actual deployment steps)
        run: echo "Deploying to staging..."
