name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Use the appropriate version

      - name: Restore NuGet packages
        run: dotnet restore ./WebApp/WebApp/WebApplication1.sln

      - name: Build application
        run: dotnet build ./WebApp/WebApp/WebApplication1.sln --configuration Release

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Use the appropriate version

      - name: Restore NuGet packages
        run: dotnet restore ./WebApp/WebApp/WebApplication1.sln

      - name: Build application
        run: dotnet build ./WebApp/WebApp/WebApplication1.sln --configuration Release

      - name: Run tests (replace with actual test commands)
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Use the appropriate version

      - name: Restore NuGet packages
        run: dotnet restore ./WebApp/WebApp/WebApplication1.sln

      - name: Build application
        run: dotnet build ./WebApp/WebApp/WebApplication1.sln --configuration Release

      - name: Deploy to staging (replace with actual deployment steps)
        run: echo "Deploying to staging..."
